### ISSUE TITLE
Please support generator syntax

### ISSUE THREAD

**Issue by YichengLiu** [huozhi/bunchee#11]
Hey bunchee maintainer! I am trying to use bunchee to compile my generator code but it just can't! Could you please add support for that feature? thank you!

**Comment by huozhi** [comment]
@YichengLiu bunchee is based on buble compiler and seems buble doesn't support async/await and generators yet https://github.com/bublejs/buble/pull/224

we can switch to babel to work out this issue

**Comment by huozhi** [comment]
@YichengLiu published bunchee@1.0.0 to resolve this
