### ISSUE TITLE
Does "react-jsx" work?

### ISSUE THREAD

**Issue by silvenon** [huozhi/bunchee#117]
This is a very cool tool, thanks for creating it! I was wondering about compiling React, is setting `"jsx": "react-jsx"` in `tsconfig.json` supposed to work? I'm getting the following error message when I try to compile a `.tsx` file:

```
Error: @rollup/plugin-typescript TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

Let me know if you need a repro.

**Comment by huozhi** [comment]
would be great to have a reproduction that I can play with it for investigation 🙏

**Comment by silvenon** [comment]
Cool! Here you go: [silvenon/repro](https://github.com/silvenon/repro/tree/bunchee/react-jsx) (the branch is `bunchee/react-jsx`)

**Comment by huozhi** [comment]
Thanks, that should be doable to respect the original `jsx` setting in tsconfig, will work on it

**Comment by huozhi** [comment]
It's released in 2.0.2 🎉

**Comment by silvenon** [comment]
It works, thanks! ❤️

I find publishing packages today still super intimidating, despite having it done so many times in the past, but bunchee makes it so much more approachable! 🎉

**Comment by huozhi** [comment]
Thanks for the kind words! ❤️ Let me know if you find out there's anything else I could make it better
