### ISSUE TITLE
Maximum call stack size exceeded on version >=2.0.2

### ISSUE THREAD

**Issue by hazae41** [huozhi/bunchee#138]
Hi, 

When I try to run [xswr](https://github.com/hazae41/xswr), a library built with bunchee version >=2.0.2 on a Next.js website, a "Maximum call stack exceeded" is thrown

Reproduction: 
1. clone xswr: `git clone https://github.com/hazae41/xswr && cd xswr`
2. install dependencies: `npm install`
3. update bunchee: `npm install --save-dev bunchee`
4. build xswr: `npm run build`
5. link xswr: `npm link`
6. go to the test directory: `cd test/next`
7. install dependencies: `npm install`
8. remove xswr: `npm remove @hazae41/xswr`
9. link xswr: `npm link @hazae41/xswr`
10. run test with Next dev: `npm run dev`
11. go to http://localhost:3000
12. click some page and the error is thrown

This doesn't happen on 2.0.1, 2.0.0, 1.9.1

Thank you!

**Comment by huozhi** [comment]
> link xswr: npm link @hazae41/xswr
This seems wired, doesn't seem to link the built package in parent directories?

I tried using `yarn` in `test/next`, and use link package version for "xswr" like `"xswr": "link:../.."` in package.json, then replacing `@hazae41/xswr` to `xswr`, it works well for `next dev` and `next build`

**Comment by hazae41** [comment]
I will try again with yarn tomorrow

**Comment by hazae41** [comment]
I tried the same steps as in the first post but with yarn (1.22.19), the same error is thrown

**Comment by hazae41** [comment]
> Why do you do npm link @hazae41/xswr, where is this package from?

It comes from the root directory, it's built at step `4` and linked at step `5`

**Comment by hazae41** [comment]
> If you publish it in a random package with latest bunchee, can you repro it in a standalone next app?

I published `@hazae41/xswr@1.0.87` (tag `debug`) with latest bunchee

**Comment by huozhi** [comment]
Closed as cannot repro
