### ISSUE TITLE
using wildcards error

### ISSUE THREAD

**Issue by pengshengjie** [huozhi/bunchee#142]
Does it support multiple entries using wildcards, for example
![image](https://user-images.githubusercontent.com/117100743/199716694-b140e417-aac3-429e-904f-17d90d240725.png)

**Comment by huozhi** [comment]
No you need to provide an entry file or you need to configure the entry and output inside package exports. Please checkout readme for detailed documentation.

**Comment by devjiwonchoi** [comment]
Hey @pengshengjie, bunchee just released support for wildcard exports as experimental!
