### ISSUE TITLE
Change the default output syntax level

### ISSUE THREAD

**Issue by huozhi** [huozhi/bunchee#151]
bunchee default output to es5, since IE11 is not supported officially anymore, the default output should change to es6 or even higher

**Comment by childrentime** [comment]
can bunchee use typescript ouput version?

**Comment by huozhi** [comment]
@childrentime yes you can specify it in tsconfig with `target` option

**Comment by childrentime** [comment]
I set it to es2018, but still get `error TS2802: Type 'IterableIterator<number>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.`  with bunchee version 2.2.0

**Comment by huozhi** [comment]
I believe you can find some information here https://github.com/huozhi/bunchee/issues/145
