### ISSUE TITLE
Upgrade to rollup v4

### ISSUE THREAD

**Issue by huozhi** [huozhi/bunchee#168]
~~Consider moving to [rolldown](https://github.com/rolldown-rs/rolldown) or use low level bundler to improve speed~~

Rollup v4 is moving to swc parser, would help a ton here

**Comment by devjiwonchoi** [comment]
Seems like rolldown isn't actively being managed, just wondering if Vite + SWC or turbopack could work along?

**Comment by huozhi** [comment]
I think might move to rollup v4 as they’re moving to swc parser. It would improve a lot I believe
