### ISSUE TITLE
Auto configure the package.json exports

### ISSUE THREAD

**Issue by huozhi** [huozhi/bunchee#182]
If you specify output formats, and your package.json is empty, you should be able to configure the exports filed in package.json.

```
bunchee exports
```

based on the "type" in package.json

can auto configure your `package.json` with the expected exports. for `"module"` type, only output one line 

```json
{
  "exports": {
     "./foo": "./dist/esm/index.mjs"
  }
}
```

For dual package we write both `import` and `require` in the export.

```json
{
  "exports": {
      "import": "./dist/esm/index.mjs",
      "require": "./dist/cjs/index.cjs"
   }
}
```

```json
{
  "exports": {
     "./foo": {
        "import": "./dist/esm/index.mjs",
        "require": "./dist/cjs/index.cjs"
     }
   }
}
```

**Comment by devjiwonchoi** [comment]
@huozhi Do you mind if I work on it?

**Comment by huozhi** [comment]
Hi @devjiwonchoi thanks for checking, I'd like to think a bit more on this command. As I also wanna show more errors for checking if you mis-configured the exports. I put an `investigating` label here for now.

But if you want to pick up any other issue, feel free to filter with "good first issue" in the issue lists 🙏 Those are ones that open for picking, thanks!

**Comment by devjiwonchoi** [comment]
Goit it. Thank you!

**Comment by huozhi** [comment]
Hey @devjiwonchoi I've updated the requirement about this feature, and I believe this will benefit a lot of people who're struggling of configuration. Do you still want to work on this cool feature?

**Comment by devjiwonchoi** [comment]
With my pleasure!

**Comment by devjiwonchoi** [comment]
@huozhi I'm confused with this line:

> and your package.json is empty

Q1: Is this feature to refactor/configure the existing exports to correct format, or to add `exports` for them based on other metas?

Q2: If the latter, how should we know `./foo`?

Q3: Dual packages meaning both `main` and `type: module` existing right?

P.S. I'm preparing for AWS exam, might not be able to work on this for a week or so.

**Comment by huozhi** [comment]
No rush for now. I feel there're still few cases need to think of. I'll try to keep updating the description here until I feel it's ready
