### ISSUE TITLE
Test against the bundled assets

### ISSUE THREAD

**Issue by huozhi** [huozhi/bunchee#208]
At the very beginning i was testing against the build assets, first run build then use the js dist files to run all the tests. After that I switched to [ts alias](https://github.com/huozhi/bunchee/blob/da9df8fb6c376b16197fb6a045b59acace073af1/test/tsconfig.json#L7-L10) that we test against source.

But as a bundler, the output asset could contain problem but the source were good, so I want to have another test that doing the job of using the dist file to test, but will only be able to run after the build.

**Comment by devjiwonchoi** [comment]
Do you mind sharing more context of the issue?

**Comment by huozhi** [comment]
@devjiwonchoi Sure! I've updated the description!

**Comment by devjiwonchoi** [comment]
Can you share your thoughts on this? I'm thinking of duplicating the `integration` test to use the assets in `dist`.

**Comment by huozhi** [comment]
Yeah basically just need two more tests, that using `dist` to run the same tests of integration and compile (unit) tests, but requires to run `pnpm build` first
