### ISSUE TITLE
Use the same exports condition when importing nested packge

### ISSUE THREAD

**Issue by huozhi** [huozhi/bunchee#213]
For instance, when pickup `react-server` condition, it should have preferr keeping to pick up `react-server` for dependencies

For instance I have a package A needs to be bundled, and it has a dependency B needs to be treated as non-external.

A has a `react-server` export condition, B also has a `react-server` condition. In the output bundles of A, `react-server` condition should contain the code of `react-server` condition from B

**Comment by kaf-lamed-beyt** [comment]
Hi @huozhi, I'd love to work on this.

Is this the file I'll be interacting with?

**Comment by huozhi** [comment]
@kaf-lamed-beyt Hi, feel free to pick up, not sure how many files will be touched

**Comment by kaf-lamed-beyt** [comment]
Awesome! 

I'm not entirely sure I understand the description of the issue, BTW. If you can add a little info, I'd appreciate it.

**Comment by kaf-lamed-beyt** [comment]
Awesome! 

I'm not entirely sure I understand the description of the issue, BTW. If you can add a little info, I'd appreciate it.

**Comment by huozhi** [comment]
Update the description with an example

**Comment by kaf-lamed-beyt** [comment]
Ayy! I'll have a look at it now. Thanks.

**Comment by huozhi** [comment]
Close as it's more for a app bundler (like webpack)'s feature which might need to specify the condition names for different type of bundles. Bunchee will focus on lib source code and won't touch much about the dependencies
