### ISSUE TITLE
Feature Request: set `outDir` name on exports, `dist` by default, read `outDir` from tsconfig

### ISSUE THREAD

**Issue by devjiwonchoi** [huozhi/bunchee#233]
Support additional option, `outDir`.

Example:

```json
{
  "exports": {
    "outDir": "./dist"
    ".": {
      "import": "index.mjs",
      "require": "index.cjs"
    },
    "./name": {
      "import": "name.mjs",
      "require": "name.cjs"
    }
  }
}
```

Will map the `outDir` to the paths.

If outDir is stated on path already, (e.g. `"./dist/name.mjs"`) skip mapping the `outDir`.

If undefined, `./dist` by default.

Q: Would there be any issue if add steps to read off from tsconfig.outDir?

**Comment by huozhi** [comment]
The design of this library wasn't indended to to add new field to `package.json`, but `outDir` from `tsconfig.json` is valid.
The problem is you still need to add the exports fields to `package.json`. but `exports.outDir` is not a valid resolution option for nodejs so we can't have it.
