### ISSUE TITLE
Refactor getExportPaths

### ISSUE THREAD

**Issue by huozhi** [huozhi/bunchee#243]
x-ref: https://github.com/huozhi/bunchee/pull/228#pullrequestreview-1563417443

One design improvement could be: keep getExportPaths simple, that reciving a resolved exports map instead of cwd and doing cwd operation

**Comment by huozhi** [comment]
@devjiwonchoi sounds good! 👍 Let's add an experimental warning for this, thanks

**Comment by devjiwonchoi** [comment]
Would you rather use chalk or no syntax highlight?

**Comment by huozhi** [comment]
I'd like to keep it simple for now, just using console.log

**Comment by huozhi** [comment]
`console.warn` is also fine as we stick to native logging without extra ascii colors
