### ISSUE TITLE
Warning displayed: `Unknown input options: onLog.`

### ISSUE THREAD

**Issue by devjiwonchoi** [huozhi/bunchee#246]
```console
devjiwonchoi@Jiwons-MacBook-Air equine % pnpm build

> equine@0.0.0 build /Users/devjiwonchoi/DevLife/OpenSource/equine
> bunchee

Unknown input options: onLog. Allowed options: acorn, acornInjectPlugins, cache, context, experimentalCacheExpiry, experimentalLogSideEffects, external, inlineDynamicImports, input, makeAbsoluteExternalsRelative, manualChunks, maxParallelFileOps, maxParallelFileReads, moduleContext, onwarn, perf, plugins, preserveEntrySignatures, preserveModules, preserveSymlinks, shimMissingExports, strictDeprecations, treeshake, watch
 ✓  Typed dist/index.d.ts - 4.83 kB
 ✓  Built dist/index.js   - 12.1 kB
✨  Finished in 732ms
```

I'm seeing this warning from several projects of mine, not sure what I'm missing. Perhaps package.json?

### Reproduction

[CodeSandBox](https://codesandbox.io/p/github/devjiwonchoi/equine/draft/exciting-satoshi?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clm4vf40m000j3b6dd0yiygls%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clm4vf40m000e3b6dsx6q9r0l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clm4vf40m000i3b6d59clqd7s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clm4vf40m000g3b6d1063wz4b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clm4vf40m000e3b6dsx6q9r0l%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clm4vf40m000d3b6d61l2ioag%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clm4vf40m000e3b6dsx6q9r0l%2522%252C%2522activeTabId%2522%253A%2522clm4vf40m000d3b6d61l2ioag%2522%257D%252C%2522clm4vf40m000g3b6d1063wz4b%2522%253A%257B%2522id%2522%253A%2522clm4vf40m000g3b6d1063wz4b%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clm4vf40m000i3b6d59clqd7s%2522%253A%257B%2522id%2522%253A%2522clm4vf40m000i3b6d59clqd7s%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clm4vf40m000h3b6dcj8k5jft%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clm4vf49j000se3je7ahj8f6d%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522id%2522%253A%2522clm4vg25z00hc3b6d0ro9p12j%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clm4vg25z00hc3b6d0ro9p12j%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### package.json

```json
{
  "name": "equine",
  "version": "0.0.0",
  "description": "minimal lichess client for node",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "bunchee",
    "test": "dotenv -e ./.env jest"
  },
  "dependencies": {
    "node-fetch": "^2.6.7"
  },
  "devDependencies": {
    "@swc/jest": "^0.2.29",
    "@types/jest": "^29.5.4",
    "@types/node": "^20.5.8",
    "@types/node-fetch": "2.6.4",
    "bunchee": "^3.6.1",
    "dotenv": "^16.3.1",
    "dotenv-cli": "^7.3.0",
    "jest": "^29.6.4",
    "typescript": "^5.2.2"
  },
  "jest": {
    "transform": {
      "^.+\\.(t|j)sx?$": "@swc/jest"
    }
  },
  "files": [
    "dist/*"
  ],
  "author": "Jiwon Choi",
  "repository": {
    "type": "git",
    "url": "https://github.com/devjiwonchoi/equine.git"
  },
  "license": "MIT",
  "keywords": [
    "chess",
    "lichess",
    "api",
    "client",
    "node"
  ],
  "engines": {
    "node": ">= 16"
  },
  "packageManager": "pnpm@8.6.12",
  "funding": "https://github.com/sponsors/devjiwonchoi"
}
```

P.S. Are you planning to open a discussion section for bunchee? This issue is more of a `help` not a bug I assume.

**Comment by huozhi** [comment]
I can't access the codesandbox link, seems not public.

> P.S. Are you planning to open a discussion section for bunchee? This issue is more of a help not a bug I assume.
I think we can leave the issues for now as there're not many yet, I can triage the issues if they're for discussion only or really broken.

**Comment by devjiwonchoi** [comment]
> I can't access the codesandbox link, seems not public.

@huozhi My bad, can you check again?

**Comment by huozhi** [comment]
Looks like it's from rollup-plugin-dts, once remove the onLog condition from its code, then the warning is gone

**Comment by devjiwonchoi** [comment]
So is it `rollup-plugin-dts` issue, or can we handle it internally?

**Comment by huozhi** [comment]
Looks like it's from rollup, I added a resolution field and it's gone

```
"resolutions": {
    "rollup": "^3.28.0"
  },
```

Upgrading rollup and other pkgs in #247
