### ISSUE TITLE
CSS support?

### ISSUE THREAD

**Issue by javierbyte** [huozhi/bunchee#258]
I'm currently using bunchee to build a very simple component library and I want to also distribute some CSS with it. My CSS is so simple that I'm happy with copying it as is. To do this, I'm using `npm-watch` to copy my file on change.

```
  "scripts": {
    "build": "bunchee ./src/index.tsx && cp ./src/style.css ./dist/main.css",
    "watch": "npm-watch"
  },
  "watch": {
    "build": {
      "patterns": [
        "src"
      ],
      "extensions": "tsx,ts,css",
      "quiet": false
    }
  },
```

I found bunchee very easy to work with js files, and I think it could benefit from a built-in CSS support so we can export files, or a way to hook into `bunchee -watch` to run some other npm script to do some work when files changes, or something else that can help with CSS distribution.

Also, great job @huozhi! as always

**Comment by huozhi** [comment]
Thanks for the feedback, was thinking to add the support for CSS recently
