### ISSUE TITLE
pkg.exports["."].import is ./dist/index.js but the file does not exist.

### ISSUE THREAD

**Issue by himself65** [huozhi/bunchee#268]
<img width="1009" alt="image" src="https://github.com/huozhi/bunchee/assets/14026360/63e09289-9da2-419d-a442-b5d427d54378">

**Comment by himself65** [comment]
temp solution:

<img width="419" alt="image" src="https://github.com/huozhi/bunchee/assets/14026360/d5ecf42e-4519-4d8a-9d8d-12fd697a4a23">

**Comment by himself65** [comment]
see https://github.com/himself65/view-link/blob/858016b1e010c0d76f2a298a0b0a8b810f6e23dc/package.json#L7-L11

**Comment by huozhi** [comment]
You're using a quite conflicted behavior of exports, having `"main"` field and `exports["."]` at the same time, please remove the `main` field if you'r eproviding multiple `exports` for "." export

**Comment by huozhi** [comment]
This is actually a bug, I did more test it's actually valid. check https://github.com/huozhi/bunchee/issues/420#issuecomment-1896480383
