### ISSUE TITLE
Support for import.meta.url

### ISSUE THREAD

**Issue by thgh** [huozhi/bunchee#275]
Hi, I wish to target both esm and cjs. The package contains a server that serves static assets. Is there a way to refer to a relative folder to serve assets from in Typescript?

I tried to use __dirname but it isn't transpiled resulting in a runtime error in the esm build.
```
ReferenceError: __dirname is not defined in ES module scope
```

I tried to use import.meta.url but it fails to build with the following error:
```
src/index.ts(1,24): error TS1343: The 'import.meta' meta-property is only allowed
when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.
      
       ⨯ RollupError: Failed to compile. Check the logs above.
```

It seems like the values in tsconfig.json don't affect the error.

**Comment by huozhi** [comment]
Thanks for filing this issue, it's an interesting, will do some investigation to see how many other similar globals and what's the best way to do it

**Comment by thecuvii** [comment]
Here's how unbuild and tsup work:

https://github.com/unjs/unbuild/blob/83ea4f050f98c6ec79feabcc88e86a2023cbba2a/src/builder/plugins/cjs.ts#L31

https://github.com/egoist/tsup/blob/8c26e63c92711d60c05aedd3cdc358530ba266c5/assets/esm_shims.js
https://github.com/egoist/tsup/blob/8c26e63c92711d60c05aedd3cdc358530ba266c5/assets/cjs_shims.js
