### ISSUE TITLE
Refactor handling entries to depend less on exports

### ISSUE THREAD

**Issue by devjiwonchoi** [huozhi/bunchee#284]
Currently, most of our bundle-related codes are depending on the incoming exports.
This is reasonable since exports are the main target of bunchee.
However, when extending features such as 'bin' or upcoming additions, tweaking the if cases and adding extra layers may be inefficient in the long run.

Therefore I'd suggest an overall refactor mainly on the `build-config`, rollup-related codes, and others that need to be modified.
This will include managing entries not only as `exports` but as the entries that include the exports and many more.

**Comment by huozhi** [comment]
The path would be from package.json (exports, bin declaration) to an exports mapping which is being used across the bundler. `bin` can be part of it in the mapping.
Love to see more refactoring to make the code more clear.
