### ISSUE TITLE
Bunchee reuses the output of 1 file for others.

### ISSUE THREAD

**Issue by samijaber** [huozhi/bunchee#312]
Reproduction steps:

- go to https://github.com/BuilderIO/hydration-overlay/blob/fix/webpack-import/ branch
- `pnpm install`
- cd `packages/lib`
- run `bunchee src/*`

`dist/next-plugin.cjs` and `dist/webpack.cjs` has the output meant for `dist/HydrationOverlay.cjs`

**Comment by huozhi** [comment]
Hi thanks for reporting, seems there's some mis-configuration with bunchee:

bunchee will detect your exports field, so you just do `bunchee` as build script will be the easy way. `bunchee src/*` is compile each file under `src/*` without giving any configuration.

1. Notice you're using `webpack` but it's external, consider adding `webpack` as `peerDepenency` or `dependencies`.
2. you need to rename your entry files to match the "export" name

```
renamed:    src/HydrationOverlay.tsx -> src/index.tsx
renamed:    src/next-plugin.ts -> src/next.ts
```
Then just run `bunchee` as build command it will build for you

```
 ✓ Typed dist/webpack.d.mts              - 562 B
 ✓ Typed dist/webpack.d.cts              - 562 B
 ✓ Typed dist/HydrationOverlay.d.mts     - 160 B
 ✓ Typed dist/HydrationOverlay.d.cts     - 160 B
 ✓ Typed dist/next-plugin.d.mts          - 885 B
 ✓ Typed dist/next-plugin.d.cts          - 885 B
 ✓ Built dist/Overlay-client-!~{001}~.js - 4 kB
 ✓ Built dist/HydrationOverlay.mjs       - 356 B
 ✓ Built dist/HydrationOverlay.cjs       - 650 B
 ✓ Built dist/webpack.mjs                - 2.54 kB
 ✓ Built dist/webpack.cjs                - 2.87 kB
 ✓ Built dist/next-plugin.mjs            - 3.36 kB
 ✓ Built dist/next-plugin.cjs            - 3.72 kB
 ✓ Finished in 1.604s
```

**Comment by samijaber** [comment]
Amazing, that works!
