### ISSUE TITLE
Entry point does not reuse another entry point's code

### ISSUE THREAD

**Issue by samijaber** [huozhi/bunchee#314]
Reproduction steps:

- go to https://github.com/BuilderIO/hydration-overlay/blob/fix/webpack-import/ branch
- `pnpm install`
- cd `packages/lib`
- run `bunchee`

`dist/next.{c,m}js` duplicate the code from `dist/webpack.{c,m}js` instead of importing it.

**Comment by huozhi** [comment]
Good case, I'll find a way to externalize the entry files

**Comment by huozhi** [comment]
Before having the support, one way to work around is write

```
import xx from <package name>/<sub export>
```

`<package name>` and `<package name>/*` will be treated as externals

**Comment by huozhi** [comment]
Fixed in 4.2.0
