### ISSUE TITLE
invalid side-effect import of class component in RSCs

### ISSUE THREAD

**Issue by samijaber** [huozhi/bunchee#315]
Reproduction steps:

- go to https://github.com/BuilderIO/hydration-overlay/blob/fix/webpack-import/ branch
- `pnpm install`
- go to `packages/lib`
- run `pnpm build`
- go to `tests/next-app-dir`
- run `pnpm dev`

The app crashes with this error:

```
Error: Object prototype may only be an Object or null: undefined
```

This is caused by the side-effect import to `react-diff-viewer` added to `packages/lib/dist/HydrationOverlay.mjs`:

```tsx
import React from "react";
import { O as Overlay } from "./Overlay-client-2JqKeDKb.js";
import "beautify";
import "react-dom";
import "react-diff-viewer"; // <---- PROBLEMATIC IMPORT

function HydrationOverlay(props) {
  return /*#__PURE__*/ React.createElement(
    React.Fragment,
    null,
    props.children,
    /*#__PURE__*/ React.createElement(Overlay, null)
  );
}

export { HydrationOverlay };

```

Removing the import fixes this. I believe that's because `react-diff-viewer` is a React Class component, which cannot be imported in React Server Components: https://nextjs.org/docs/messages/class-component-in-server-component

(Not sure why the error shown is an obfuscated one, but I got the class error when downgrading the `react-diff-viewer` dependency to 3.0.2)

Why are these side effect imports even being added? Any workaround"

**Comment by huozhi** [comment]
Looks like it's rollup's behavior, will fix it
