### ISSUE TITLE
Watch mode seems not working

### ISSUE THREAD

**Issue by promer94** [huozhi/bunchee#36]
# Repro Steps 
1. ```git clone https://github.com/promer94/test-bunchee.git``` 
2.  ```yarn install && yarn watch```
3.  modify the ```src/index.ts```, the output got rebuild but keep the same result  

## Additional Context
bunchee version 1.5.4
node version 12.18.3

**Comment by huozhi** [comment]
Thanks for reporting! This only effects typescript assets so far, it's an issue on `@rollup/plugin-typescript`, tracked in https://github.com/rollup/plugins/issues/860

**Comment by huozhi** [comment]
@promer94 should be resolved, just merged a PR to adopt bunchee 1.6.2 on swr
