### ISSUE TITLE
Feature: output tsconfig.json like prepare does for build

### ISSUE THREAD

**Issue by huozhi** [huozhi/bunchee#364]
If you're using ts but without `tsconfig.json`, and when you run `bunchee`, it should write a `tsconfig.json` file for your project

**Comment by nnecec** [comment]
The requirement is: if detect you're using TypeScript, and there is no tsconfig.json, write a tsconfig.json file at `cwd` path?

**Comment by huozhi** [comment]
@nnecec yes, correct!
