### ISSUE TITLE
Feature: Don't exit command in watch mode even if the code throw an error.

### ISSUE THREAD

**Issue by nnecec** [huozhi/bunchee#372]
Usually, I'm developing and fixing bugs in watch mode. But when I use bunchee, it always exits watch mode when I write and save the error code. 

Like type error and ts-check error, these errors are throw and exit command.

I guess developers don't want exit watch command while developing, am I right?

**Comment by huozhi** [comment]
Sounds like a bug, feel free to send a PR if you know how to fix it! 🙏
