### ISSUE TITLE
src/index.ts(1,15): error TS2459: Module '"a/server"' declares 'FileRouter' locally, but it is not exported.

### ISSUE THREAD

**Issue by juliusmarminge** [huozhi/bunchee#382]
### Reproduce

`pnpm i && pnpm build`

![CleanShot 2024-01-11 at 22 44 03@2x](https://github.com/huozhi/bunchee/assets/51714798/0cab0600-44b3-4cbc-8aac-c786a46f9fed)

Probably some weird config option that causes this, but the types aren't getting resolved:

![CleanShot 2024-01-11 at 22 45 49@2x](https://github.com/huozhi/bunchee/assets/51714798/63a897cd-f4ed-431b-b388-9e25e1bf3ccf)

**Comment by huozhi** [comment]
@juliusmarminge I tested against the repo and found that you can use the following patch to get rid of the errors

```diff
diff --git a/packages/a/package.json b/packages/a/package.json
index 7adeca4..5a7b607 100644
--- a/packages/a/package.json
+++ b/packages/a/package.json
@@ -74,8 +74,7 @@
     },
     "./internal/types": {
       "types": "./dist/internal/types.d.ts",
-      "import": "./dist/internal/types.mjs",
-      "require": "./dist/internal/types.js"
+      "default": "./dist/internal/types.js"
     }
   },
   "typesVersions": {
diff --git a/packages/a/src/server.ts b/packages/a/src/server.ts
index a178b44..632eb74 100644
--- a/packages/a/src/server.ts
+++ b/packages/a/src/server.ts
@@ -76,3 +76,5 @@ export const createServerHandler = <TRouter extends FileRouter>(
 
 export const extractRouterConfig = (router: FileRouter) =>
   buildPermissionsInfoHandler({ router })();
+
+export { type FileRouter }
\ No newline at end of file
```

* 1st, Export the type that missing in `packages/a`
* 2nd, The reason I change the "./internal/types" to only having `default` export and types, so it will only generate one type file and TS only be confused about the types of mjs and cjs.

This will make it work, but very good feedback. I think in the future it could have more validations about types to help configure correctly
