### ISSUE TITLE
bug: `bunchee -w` kills process

### ISSUE THREAD

**Issue by juliusmarminge** [huozhi/bunchee#383]
Running bunchee with `-w` flag and a build fails kills the process:

Repo: https://github.com/juliusmarminge/buncheeee

`pnpm i && pnpm dev`:

![CleanShot 2024-01-11 at 23 03 26@2x](https://github.com/huozhi/bunchee/assets/51714798/157d8c1a-e6b8-41e6-8ce2-7c731abb5a04)

Would be nice to be able to fix the error and get recompilation automatically

**Comment by huozhi** [comment]
This is fixed in #375 and shipped in [v4.3.2](https://github.com/huozhi/bunchee/releases/tag/v4.3.2)

**Comment by juliusmarminge** [comment]
Ah sorry, was on 4.3.1
