### ISSUE TITLE
Multiple runtime will read the same input file

### ISSUE THREAD

**Issue by himself65** [huozhi/bunchee#413]
https://github.com/huozhi/bunchee#multiple-runtime

for this input

```json
  "exports": {
    ".": {
      "types": "./dist/index.d.mts",
      "edge-light": "./dist/edge.mjs",
      "import": "./dist/index.mjs",
      "require": "./dist/index.js"
    }
  },
```

bunchee will always read index.ts but output to `edge.mjs` and others output.

I expect to read different inputs and generate different outputs.

**Comment by huozhi** [comment]
You can use `index.edge-light.ts` to have the different output, `index.<special export condition>.ts` is the convention for different community standard conventions. So far we suppor `development`, `production`, `edge-light`, `react-server`, `react-native`.

Worth to update the docs a bit to clarify that

**Comment by himself65** [comment]
> You can use `index.edge-light.ts` to have the different output, `index.<special export condition>.ts` is the convention for different community standard conventions. So far we suppor `development`, `production`, `edge-light`, `react-server`, `react-native`.
> 
> Worth to update the docs a bit to clarify that

Thanks for the feedback. I will try that
