### ISSUE TITLE
conditional exports compatibility with moduleResolution `node`

### ISSUE THREAD

**Issue by himself65** [huozhi/bunchee#427]
allow to publish package inside the `dist`

**Comment by himself65** [comment]
```
dist
	index.d.ts
	index.js
	a.d.ts
	a.js
package.json
```

```ts
import 'module/a' // <- will error when moduleResolution is node
```

allow output to be 

```
dist
	index.d.ts
	index.js
	a.d.ts
	a.js
	package.json
```

And we publish inside the dist

**Comment by huozhi** [comment]
It's kinda solved in #426 that we generated the relative types then they'll import the type from `"./a"` instead of `"module/a"`. Will publish once there're some more issues fixed later 🙏 stay tuned

**Comment by himself65** [comment]
Workaround https://github.com/run-llama/LlamaIndexTS/pull/451

**Comment by himself65** [comment]
I think my approach will be the most compatible way

**Comment by huozhi** [comment]
Not sure I understand your workaround..but I don't think it's an issue anymore in 4.4.2 since there's no `module/a` gonna be generated, instead it will be a relative path for the types.
