### ISSUE TITLE
non-export shared modules cause dual classes

### ISSUE THREAD

**Issue by himself65** [huozhi/bunchee#441]
```txt
node_modules/class-module
	package.json
	index.ts
	module.ts
	shared.ts
```

```json
{
	"name": "class-module"
	"exports": {
		".": "./dist/index.js"
		"./module": "./dist/module.js"
	}
}
```

```ts
// index.ts
import { Class } from './shared'

export * from './module'
export function isClass(c: unknown) {
	return c instanceof Class
}
```

```ts
// module.ts
import { Class } from './shared'
export function createClass() {
	return new Class()
}
```

```ts
// shared.ts
export class Class {}
```

### User Side

```js
import { createClass, isClass } from 'class-module'

isClass(createClass())	// <-- error
```

**Comment by himself65** [comment]
If I wrote exports too many, cause https://github.com/huozhi/bunchee/issues/423 again

**Comment by huozhi** [comment]
Do you mean shared.ts is not actually being shared because it's being bundled on both side? I didn't see the error locally,  what's the actual error you're seeing?

**Comment by huozhi** [comment]
Hi, I got a new beta version 5.0.0-beta.2 of bunchee released on npm, which has feature like shared module code splitting. Would love to hear your feedback about it! :pray: 

Having sth like `mymodule.shared-runtime.js` can make sure all the things are shared. More context in #480
