### ISSUE TITLE
Ability to override build target

### ISSUE THREAD

**Issue by shuding** [huozhi/bunchee#45]
It seems that ES5 is always the build output target, and will override the project tsconfig value:

https://github.com/huozhi/bunchee/blob/1a4ade8f33eb676744e8bda59a8c359523ff0ca9/src/rollup-config.ts#L85

**Comment by huozhi** [comment]
@shuding This was intended to make sure all the output are compatible with es5, mostly for browser compatibility. Override it inside the bundler to let user configure less.
Very good callout, I was also wondering should we use mordern syntaxes for node.js project. What's your case here that you'd like to use other `target` besides ES5?

**Comment by shuding** [comment]
I think ES5 can be a good default, but shouldn't override user's intention in tsconfig. For example I want to try ESNext to drop IE support.

**Comment by huozhi** [comment]
TIL from styfle that we can use node version to specific ecmascript version with babel

```
node10 => es2018
node12 => es2019
node14 => es2020
```

I'll think of that later, maybe to provide a CLI option instead consuming from tsconfig to make the behavior consistent between js and ts inputs

**Comment by shuding** [comment]
Wow that’s interesting… but eventually I believe Bunchee needs its own config file. 😄

**Comment by huozhi** [comment]
Short term, consider esbuild as an alternative for testing?

**Comment by koba04** [comment]
IE is now officially out of support, so it's time to change the target version.
https://github.com/vercel/swr/discussions/2095

**Comment by huozhi** [comment]
I'm waiting for a change on swc side so that I could adopt swc, then the target will easier to control

**Comment by huozhi** [comment]
> Wow that’s interesting… but eventually I believe Bunchee needs its own config file. 😄

@shuding I think you're right, I start to thinking in this way recently, but the idea is to only have configure in package.json when case becomes complicated such as multi-filed exports
