### ISSUE TITLE
Use typescript without generate d.ts

### ISSUE THREAD

**Issue by hyoban** [huozhi/bunchee#454]
https://github.com/huozhi/bunchee/blob/fb1214e1bd9d36536189357611909b698ca8b3e5/src/build-config.ts#L212

https://github.com/huozhi/bunchee/blob/fb1214e1bd9d36536189357611909b698ca8b3e5/src/build-config.ts#L258

If I remove "types" in "package.json", should the dts plugin not be applied?

**Comment by huozhi** [comment]
Why would you want this behavior?

**Comment by hyoban** [comment]
For an example, [release-it](https://github.com/release-it/release-it) do not have type definition. But i still want use typescript to write plugin for it. Ship type in my plugin package is useless, because we will not reference it in code.

**Comment by huozhi** [comment]
Sounds you only need to define a type for `release-it` module to use? Then you can still import the type for it, at least tsconfig should be able to resolve and generate type for that 🤔 

Would love to see the code example there. IMO we shouldn't stop generating types for ts project, cause that's what ts is for.

**Comment by huozhi** [comment]
Sounds reasonable, or maybe to skip the types generation for types. `--no-dts` sounds a good option to be introduced
