### ISSUE TITLE
could not find a copy of typescript to link in bunchee

### ISSUE THREAD

**Issue by wendellhu95** [huozhi/bunchee#46]
Tried to use bunchee in a TypeScript 4 project. Seems that bunchee doesn't support TypeScript 4 at the moment.

**Comment by huozhi** [comment]
By default bunchee includes Typescript v3.9.x inside as a dependency. If you want to use your own version, just install typescript as another dev dependency then bunchee will automatically pick it.

Thanks for reporting, I'll add this to the doc.

**Comment by huozhi** [comment]
I think the optional dependency will also effect this. can you try version 1.6.1 @wendellhu95?

```
yarn add -D bunchee typescript
```
