### ISSUE TITLE
client and server boundary code split are not accurate

### ISSUE THREAD

**Issue by huozhi** [huozhi/bunchee#477]

**Comment by KajSzy** [comment]
I'm using `bunchee` to create a toolbar for nextjs that combines client and server components.
In my project when file with `'use client'` imports another file with `'use server'` directive `bunchee` outputs file with both directives.

You can see repro here https://github.com/KajSzy/next-cache-toolbar/tree/rc/0.2.0

File `src/feature/cache-panel/cache-refresh-data.tsx` is outputs with
```js
'use server';
'use client';
```

**Comment by huozhi** [comment]
Thanks fore reporting @KajSzy , I was looking at your codebase now and testing locally but didn't find the repro. Are you still having the issue on that branch?

**Comment by KajSzy** [comment]
I've found a fix to that issue, removing `'use server'` from entry file made all other chunks to split more properly.
Also I've updated to beta version `5.0.0-beta.4`
https://github.com/KajSzy/next-cache-toolbar/commit/9d6684477fc66c673b95190534f2aacc8bd83b2f#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405L1

**Comment by huozhi** [comment]
Good to hear that 👏

**Comment by huozhi** [comment]
This was raised in a SWR PR but also resolved. Closed this as cancelled
