### ISSUE TITLE
Loading indicator in terminal during building

### ISSUE THREAD

**Issue by huozhi** [huozhi/bunchee#512]
Would be nice if we can have a loading bar when the command starts as some project might be big to build that hangs for a while

**Comment by evnxprk** [comment]
What do you mean by a loading bar? Like a bar in the middle of the screen that shows when the page would be fully loaded?

**Comment by huozhi** [comment]
I renamed the title, want to have sth like loading indicator while building such like [ora](https://github.com/sindresorhus/ora/)

**Comment by evnxprk** [comment]
Okay, I can do that. I was just running into an issue installing bunchee though. 

User
when i try to install bunchee using this command: npm install --save-dev bunchee it says this error: npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:./

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/beaw/.npm/_logs/2024-04-04T17_13_13_362Z-debug-0.log

**Comment by devjiwonchoi** [comment]
@evnxprk Hi, are you currently working on this?
