### ISSUE TITLE
`--dts` does not generate `.d.ts` for JavaScript files

### ISSUE THREAD

**Issue by devjiwonchoi** [huozhi/bunchee#517]
repro: https://github.com/devjiwonchoi/repro-bunchee-dts
bunchee version: 5.1.2

**Comment by devjiwonchoi** [comment]
requires tsconfig, silly me.

**Comment by devjiwonchoi** [comment]
But, could this be supported? create `.d.ts` for JS without js/tsconfig. Or else, need action to inform that requires tsconfig

**Comment by huozhi** [comment]
if you run `bunchee` directly and let it detect the project it can generate tsconfig for you. We can warn for them that tsconfig is missing, but I'm not sure if we should generate one for them yet since CLI could run from anywhere then `cwd` can be anywhere as well

**Comment by huozhi** [comment]
Ah yeah you're right. `--dts` it's kinda always enable if tsconfig.json is present. So it's not a very useful flag...

Ideally if you have `<cwd>/tsconfig.json` it should be enabled, if you don't have tsconfig.json it's always disabled. We should probably just drop that flag but still keep `--no-dts`

**Comment by devjiwonchoi** [comment]
Thanks for the clarification! 😆
