### ISSUE TITLE
Build crashing with OOM

### ISSUE THREAD

**Issue by Makisuo** [huozhi/bunchee#533]
I have a package with a lot of entries and it seems to consume overly much Memory, aswell as crashing with Out of Memory since  reaching some threshold of entry files.

Any way for me to limit bunchees concurrent building or setting Memory Limits for my builds to not crash from it?

```tsx
@pixelshades/styles:build: <--- JS stacktrace --->
@pixelshades/styles:build: 
@pixelshades/styles:build: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
@pixelshades/styles:build: ----- Native stack trace -----
@pixelshades/styles:build: 
@pixelshades/styles:build:  1: 0x100da959c node::Abort() [/Users/A200286255/Library/Application Support/fnm/node-versions/v20.11.1/installation/bin/node]
```

Here is also the package responsible for it:

https://github.com/telekom/pixelshades/blob/main/packages/styles/package.json

**Comment by huozhi** [comment]
@Makisuo I'm not seeing this problem with `bunchee@5.1.5` which is used on main branch now, are you still seeing the issue?

**Comment by huozhi** [comment]
I tested with removing that flag and it still works for me
