### ISSUE TITLE
Production build overriding development build

### ISSUE THREAD

**Issue by amannn** [huozhi/bunchee#548]
Apparently the order in which you define the `development` and `production` conditions has an effect on the resulting bundle. If you have a library with multiple entry points, let's say:

- `./`
- `./core`
- `./react`

… where `./` re-exports from the sub pacakges, then `index.development.mjs` will point to `core.production.mjs`.

Repro: https://github.com/amannn/bunchee-test/commit/cc17248169a77d1e8babcd24a7fe9105454f845e

```
// dist/index.development.mjs
export * from './core.production.mjs';
export * from './react.production.mjs';
```

Listing `production` first is unfortunately not a viable workaround, as in this case `dist/index.production.mjs` will point to `core.development.mjs`.

**Comment by huozhi** [comment]
This is a very interesting bug 👀
