### ISSUE TITLE
The `src` folder was deleted when exporting a TypeScript file in the "development" field.

### ISSUE THREAD

**Issue by thecuvii** [huozhi/bunchee#555]
When exporting a TypeScript file with the development field, such as `src/index.ts`, there will be an `Error [RollupError]: Could not resolve entry module "src/index.ts".` error, and the `src` folder was deleted.

``` json
  "exports":{
    "development":"./src/index.ts",
    "default":"./dist/index.mjs"
  },
```

https://github.com/huozhi/bunchee/assets/11806619/f1ad3eb9-d402-475d-95d2-289a9da8c910

repro: https://github.com/thecuvii/bunchee-development-repro

**Comment by thecuvii** [comment]
I use this pattern in a monorepo, so I don't have to run a "dev" command for each package.
The main issue here is that the "src" folder should not be deleted, as I may lose all my uncommitted source files.

**Comment by huozhi** [comment]
Yea that's right, the `src/` folder or source files shouldn't be auto deleted. I can fix that later.
But why it's using `bunchee` if this package doesn't need to use bunchee? IMO it's weird to determine what to do if your input path is same as output or if your output is ts file

**Comment by thecuvii** [comment]
LOL, I use `bunchee`, just trying to figure out if it's possible to export a TypeScript file for development only, and then encounter this problem.

**Comment by huozhi** [comment]
yea should def keep the files there
