### ISSUE TITLE
Shared modules should inherit file extension (e.g. `.mjs`)

### ISSUE THREAD

**Issue by amannn** [huozhi/bunchee#557]
Another week, another bug report :).

I noticed when you have a build that generates `.mjs` files (since the package uses `type: 'commonjs'`), then shared modules of the entry points will use the `.js` extension. This results in consumer errors if the shared module has further imports since all modules that use ESM in this graph should use the `.mjs` extension.

Reproduction: [`./dist/esm/core.mjs`](https://github.com/amannn/bunchee-test/blob/41cd541ddf0c61774981ad7a08bcfc41f3873cd4/dist/esm/core.mjs#L1)

In the linked example this works, but if `utils-shared-BdVwpBM3.js` would have another import (e.g. `import Link from 'next/link'`) then this would break:

```
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
```

**Comment by amannn** [comment]
Hmm, same seems to be true for separate chunks that are created via the `'use client'` split: [`react.mjs`](https://github.com/amannn/bunchee-test/commit/6b8702b938daa54ff93e7aedc9581c00552b1754#diff-416df81ab56956fa7b3c2218ad3a0a2eb44d33bfebc0ebb0dbfd5c381017976b).

**Comment by huozhi** [comment]
I changed the feature to experimental, probably still need to use a separate entry to achieve it for now 😢 The spit chunks feature is quite limited for do this automatically with rollup. I'm still exploring the other ways to do it
