### ISSUE TITLE
Add `--dts-resolve` flag like tsup

### ISSUE THREAD

**Issue by hyoban** [huozhi/bunchee#560]
When I patch some dependencies locally, I will move them to dev dependencies and bundle them, but the type will not be bundled. It would be great to have a `--dts-resolve` flag like tsup.

- https://tsup.egoist.dev/#generate-declaration-file
- https://github.com/egoist/tsup/blob/dev/src/rollup/ts-resolve.ts

**Comment by SukkaW** [comment]
We need to pass `respectExternal` to `rollup-plugin-dts` for this to work.
