### ISSUE TITLE
warn or auto-update if package.json#files doesn't includes output files

### ISSUE THREAD

**Issue by himself65** [huozhi/bunchee#591]
I have tons of output files that's not inside `./dist`, sometimes I forget to add that directory

**Comment by huozhi** [comment]
Can you use `"files": ["dist"]`? or is there any reason you need to exclude certain things.

Good call on checking the `files` field for publishing purpose still 👍

**Comment by himself65** [comment]
We cannot put output into "dist" files for compatibility reason.

See https://github.com/andrewbranch/example-subpath-exports-ts-compat/tree/main

For now we are using "extensionless" way to support all ts format

**Comment by huozhi** [comment]
I see, there're files outside of `dist` like node10 entry files?

**Comment by himself65** [comment]
yes
