### ISSUE TITLE
[FRQ] - Prevent generating client files

### ISSUE THREAD

**Issue by ValenCassa** [huozhi/bunchee#592]
Is there any way to prevent bunchee from generating client files? These files use `__node_cjsModule.createRequire` which Vite doesn't support. Polyfills don't seem to work either so I'd like to skip generating these all together if possible.

**Comment by huozhi** [comment]
Can you share a repro with your case, I'm not folliwing what client files here referring to and why it's related to `__node_cjsModule.createRequire`

**Comment by ValenCassa** [comment]
> Can you share a repro with your case, I'm not folliwing what client files here referring to and why it's related to `__node_cjsModule.createRequire`

Ah yeah, I'm sorry. I'll have a repro for tomorrow,  but I'm talking about the `[entry]-client` files. Thought those files automatically add `__node_cjsModule.createRequire` for some reason, but I guess it's because I'm using cjs modules? I see the file is importing both `luxon` and `relay-runtime` so it might be because of that

**Comment by huozhi** [comment]
`-client` is client boundary code that marked by `"use client"`, the require could relate you're using `require` in source code or it could be a bug? Need to see the repro

**Comment by ValenCassa** [comment]
Yep, I'm not using any `use client`s or `require`s, it's pretty late here already but I'll have something for tomorrow

**Comment by huozhi** [comment]
Not sure the exact issue is yet, but I added some improvements in `esm-shim` plugin, hopefully it can cover your case
