### ISSUE TITLE
regeneratorRuntime is not defined (`--target node`)

### ISSUE THREAD

**Issue by Flandre-X** [huozhi/bunchee#63]
When I try to bundle a JavaScript library that uses async functions and then use that library, I get `ReferenceError: regeneratorRuntime is not defined`, even when using `--target node`.

I found that the issue is resolved by adding `{ target: { node: "16" } }` to the options of `babel-preset-o` in `createInputConfig` in `src/rollup-config.ts`, since instead of the `async`/`await` keywords being transformed to use `regeneratorRuntime`, they are just passed through to the output as is. Though I'm not sure exactly what value `node` should be instead of `"16"`. Also, perhaps `esmodules: true` should be also added to `target` like it was before? (see below)

https://github.com/huozhi/bunchee/blob/9b67e9567ca7d7aad8246b1f816925c9c1ce2955/src/rollup-config.ts#L60-L63

**Comment by huozhi** [comment]
Thanks for reporting, regenerator definition is missing for javascript usage with babel but not missing in typescript side. Very good catch

**Comment by huozhi** [comment]
@Flandre-X Can you try the new version 1.7.3 to see if it solves your problem?

**Comment by Flandre-X** [comment]
@huozhi Yup it works, thanks for the fix!
