### ISSUE TITLE
Build issues with 1.8.4

### ISSUE THREAD

**Issue by zplata** [huozhi/bunchee#77]
Hi, I tried to build a react project using Bunchee w/ `v.1.8.4` and looks like there might be some syntax issue going on?

Repo: https://github.com/rive-app/rive-react

<img width="718" alt="Screen Shot 2022-05-26 at 2 47 03 PM" src="https://user-images.githubusercontent.com/5685058/170565677-e82c0d35-f0f3-4655-a7c7-15e557488409.png">

**Comment by huozhi** [comment]
Hi, thanks for reporting! Can you try bumping version to 1.8.5 to see if the issue is gone?

**Comment by zplata** [comment]
Looking good! Thanks for the quick turnaround 🙌

**Comment by huozhi** [comment]
Thank you for choosing bunchee 😄
